artifacts_dir: artifacts

data_ingestion:
  root_dir: "C:/Users/Saif/Downloads/chicken fecal data"
  source_csv: "C:/Users/Saif/Downloads/chicken fecal data/train_data.csv"
  image_dir: "C:/Users/Saif/Downloads/chicken fecal data/Train"
  test_size: 0.2
  random_state: 42

model:
  model_dir: artifacts/models
  model_name: chicken_disease_model.h5

logs:
  log_dir: logs
  log_file: train.log
